config/routes.rb
Rails.application.routes.draw do

  root "pages#home"
  resources :articles
  get 'signup', to: "users#new"
  resources :users, except: [:new]
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  resources :categories

end

app/models/article.rb
class Article < ActiveRecord::Base
    belongs_to :user
    has_many :article_categories
    has_many :categories, through: :article_categories
    validates :title, presence: true, length: {minimum: 3, maximum: 55}
    validates :description, presence: true
    
    def self.search(params)
        articles = all
        articles = where("title like ? or description like?", "%#{params[:search]}%", "%#{params[:search]}%") if params[:search]
        articles
    end
    
end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
    belongs_to :article
    belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :article_categories
    has_many :articles, through: :article_categories
    validates :name, presence: true, length: {minimum: 2, maximum: 13}, uniqueness: {case_sensitive: true}
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :articles, dependent: :destroy
    before_save {self.email = email.downcase}
    validates :username, presence: true, length: {minimum: 3, maximum: 30}, uniqueness: {case_sensitive: false}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, uniqueness: true, format: {with: VALID_EMAIL_REGEX}
    has_secure_password
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?
  
  def current_user
   @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def logged_in?
    !!current_user
  end
  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in"
      redirect_to root_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit,:update,:destroy]
    before_action :require_user, only: [:new, :edit, :destroy]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def index
        @articles = Article.order("updated_at DESC").search(params).paginate(page: params[:page], per_page: 5)
    end
    def new
        @article = Article.new
    end
    def create
        #render plain: params[:article].inspect
        @article = Article.new(article_params)
        @article.user = current_user
        if @article.save
            flash[:notice] = "Пост успешно создан!"
          redirect_to articles_path  
        else
            render "new"
        end
    end
    
    def show
    end
    def edit
    end
    def update
        if @article.update(article_params)
            flash[:notice] = "Пост обнoвлен!"
            redirect_to article_path(@article)
        else
            render "edit"
        end
    end
    def destroy
        @article.destroy
        flash[:notice] = "Пост успешно удален!"
        redirect_to articles_path
    end
    private
    def article_params
        params.require(:article).permit(:title, :description, category_ids: [])
    end
    def set_article
        @article = Article.find(params[:id])
    end
    def require_same_user
        if current_user != @article.user && !current_user.admin?
            flash[:danger] = "this is not ur article mazafaka"
            redirect_to articles_path
        end
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :require_admin, except: [:show, :index]
    
    
    def index
        @categories = Category.all
    end
    
    def show
        @category = Category.find(params[:id])
        @category_articles = @category.articles
        @category_articles = @category.articles.paginate(page: params[:page], per_page: 4)
    end
    
    def new
        @category = Category.new
    end
    
    def edit
        @categories = Category.find(params[:id])
    end
    
    def update
        @categories = Category.find(params[:id])
        if @category.update(category_params)
            flash[:success] = "Updated"
            redirect_to category_path(@category)
        else
            render 'edit'
        end
    end
    
    def create
        @category = Category.new(category_params)
        if @category.save
            flash[:notice] = "Категория была создана!"
          redirect_to categories_path
        else
            render "edit"
        end
    end
    
    def destroy
        @category.destroy
        flash[:success] = "Категория успешно удалена!"
        redirect_to categories_path
    end
    private
    
    def category_params
        params.require(:category).permit(:name)
    end
    
    def require_admin
        if !logged_in? || (logged_in? and !current_user.admin?)
            flash[:danger] = "Only admin user can perform this action"
            redirect_to categories_path
        end
    end
    
end

app/controllers/pages_controller.rb
class PagesController <ApplicationController
    
    def home
        redirect_to articles_path if logged_in?
    end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
    
    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:success] = "Logged in!"
            redirect_to user_path(user)
        else
            flash.now[:danger] = "Something went wrong"
            render 'new'
        end
    end
    
    def destroy
        session[:user_id] = nil
        flash[:success] = "Logged out"
        redirect_to root_path
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_user, only: [:show,:edit,:destroy]
    before_action :require_same_user, only: [:destroy]
    def index
        @users = User.paginate(page: params[:page], per_page: 5)
    end
    
    def show
        @user = User.find(params[:id])
        @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
    end
    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            flash[:success] = "Signed in"
            redirect_to root_path
        else
            render "new"
        end
    end
    def edit
        @user = User.find(params[:id])
        require_same_user
    end
    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            flash[:success] = "Updated!"
            redirect_to user_path(@user)
        else
            render "edit"
        end
    end
    def new
        @user = User.new
    end
    def destroy
        @user = User.find(params[:id])
        @user.destroy
        flash[:success] = "User deleted"
        redirect_to users_path
    end
    private
    def user_params
        params.require(:user).permit(:username, :email,:password)
    end
    def require_same_user
        if !logged_in? && !current_user != @user
            flash[:danger] = "Only admin can perfom this action"
            redirect_to users_path
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<div class="col-sm-offset-2 col-sm-8">
  <% if  @article.errors.any? %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <% @article.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
    <% end %>
  </div>
  <% end %>
  <%= form_for @article do |f| %>
         <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class:"form-control", placeholder: "Название поста" %>
        </div>
        <div class="form-group">
          <%= f.label :description %>
          <%= f.text_area :description,class:"form-control", rows:10, placeholder:"Вас пост" %>
          
        </div>
          <div class="form-group">
          <%= f.collection_check_boxes :category_ids, Category.all,:id, :name do |cb|%>
            <% cb.label(class: "checkbox-inline input-checkbox") {cb.check_box(class:"check-box") + cb.text}%>
          <% end %>
          
        </div>
        <%= f.submit "Сохранить", :class => "btn btn-lg btn-success pull-right" %>
  <% end %>
</div>

app/views/articles/edit.html.erb
<div class="text-center">
    <h1>Изменить пост</h1>
    <%= render "form"%>
</div>

app/views/articles/index.html.erb
<div class="container text-center">
  <h1>All articles</h1>
  <h4><%= link_to "Новый пост", new_article_path %></h4>
 
 
  <div class="col-sm-offset-3 col-sm-6">
   <%= will_paginate @articles %>
  
  <% @articles.each do |article| %>
  <div class="panel panel-default">
   <div class="panel-heading">
    <h2><%= article.title %></h2>
   </div>
  <div class="panel-body">
    <%= article.description%>
  </div>
  <div class="panel-footer ">
  <% if article.categories.any? %>
    <% article.categories.each  do |category| %>
     <%= link_to category.name, category_path(category),class: "badge" %>
    <% end %> 
   <% end %>
   <%= link_to "Просмотреть", article_path(article), class:"btn btn-xs btn-primary"%>
   <% if current_user == article.user %>
   <%= link_to "Обновить", edit_article_path(article),class:"btn btn-xs btn-success"%>
   <%= link_to "Удалить", article_path(article), 
                          method: :delete, data: {confirm: "Are you sure?"}, 
                          class:"btn btn-xs btn-danger"
                          %>
   <% end %>
   <%#= article.updated_at.strftime("%H:%M:%S, %d/%m/%y") %>
   Last update: <%= time_ago_in_words(article.updated_at) %> ago
   by <%#= article.user.username %>
  </div>
</div>
  <% end %>
   <%= will_paginate @articles%>
</div>
 </div>

app/views/articles/new.html.erb
<div class="container text-center">
  <h2>Create article</h2>
  <%= render 'form'%>
</div>

app/views/articles/show.html.erb
<div class="col-sm-10 text-center">
    <h2 class="page-header"><%= @article.title %></h2>
    <p>дата: <%= @article.updated_at.strftime("%H:%M:%S, %d/%m/%y") %></p>
    <div class="panel panel-default">
        <div class="panel-body">
            <%= @article.description %>
        </div>
    </div>
</div>
    <div class="btn-group pull-right" role="group" aria-label="...">
        <% if !logged_in or current_user == article.user || current_user.admin? %>
            <%= link_to "Обновить", edit_article_path(@article), class: "btn btn-primary"%>
            <%= link_to "Удалить", article_path(@article), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-primary" %></td>
        <% end %>
        <%= link_to "Все посты", articles_path, class: "btn btn-primary" %>
    </div>

</div>

app/views/categories/edit.html.erb
<div class="col-sm-offset-2 col-sm-8">
  <% if  @category.errors.any? %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <% @category.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
    <% end %>
  </div>
  <% end %>
  <%= form_for @category do |f| %>
         <div class="form-group">
          <%= f.label :Name %>
          <%= f.text_field :name, class:"form-control", placeholder: "Categoy name" %>
        </div>
        <div class="col-offset-3">
          <%= f.submit "Edit category", :class => "btn btn-md btn-success" %>
        </div>
  <% end %>
</div>

app/views/categories/index.html.erb
<h1>All categories</h1>
<ul>
    <% @categories.each do |category|%>
        <li>
            <%= link_to category.name, category_path(category), class:"btn btn-lg btn-primary" %>
            <%= category.articles.count %>
        </li>
    <% end %>
</ul>

app/views/categories/new.html.erb
<div class="col-sm-offset-2 col-sm-8">
  <% if  @category.errors.any? %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <% @category.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
    <% end %>
  </div>
  <% end %>
  <%= form_for @category do |f| %>
         <div class="form-group">
          <%= f.label :Name %>
          <%= f.text_field :name, class:"form-control", placeholder: "Categoy name" %>
        </div>
        <div class="col-offset-3">
          <%= f.submit "Add category", :class => "btn btn-md btn-success" %>
        </div>
  <% end %>
</div>

app/views/categories/show.html.erb
<h1><%= @category.name %>
    <%=link_to "Edit category", edit_category_path(@category), class:"btn btn-xs btn-success" %>
</h1>
<div class="col-sm-offset-3 col-sm-6">
  
  <% @category_articles.each do |article| %>
  <div class="panel panel-default">
   <div class="panel-heading">
    <h2><%= article.title %></h2>
   </div>
  <div class="panel-body">
    <%= article.description%>
  </div>
  
  <div class="panel-footer ">
   <% if article.categories.any? %>
    <% article.categories.each  do |category| %>
     <%= link_to category.name, category_path(category),class: "badge" %>
    <% end %> 
   <% end %>
   <%= link_to "Просмотреть", article_path(article), class:"btn btn-xs btn-primary"%>
   <% if logged_in? and current_user == article.user || current_user.admin? %>
    <%= link_to "Обновить", edit_article_path(article),class:"btn btn-xs btn-success"%>
    <%= link_to "Удалить", article_path(article), 
                          method: :delete, data: {confirm: "Are you sure?"}, 
                          class:"btn btn-xs btn-danger"
                          %>
   <% end %>                    
   <%#= article.updated_at.strftime("%H:%M:%S, %d/%m/%y") %>
   Last update: <%= time_ago_in_words(article.updated_at) %> ago
   by <%= article.user.username %>
  </div>
</div>
  <% end %>
   
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to "NAUDA", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
            <%= link_to "Все посты", articles_path %>
        </li>
        <li>
            <%= link_to "Users", users_path %>
        </li>
        <li>
            <%= link_to "Categories", categories_path %>
        </li>
      </ul>
      <!--<form class="navbar-form navbar-left">-->
      <!--  <div class="form-group">-->
      <!--    <input type="text" class="form-control" placeholder="Search">-->
      <!--  </div>-->
      <!--  <button type="submit" class="btn btn-default">Submit</button>-->
      <!--</form>-->
      <%= form_tag articles_path,class: "navbar-form navbar-left", method: :get do %>
        <%= text_field_tag :search,'', class:"form-control"%>
        <%= submit_tag "Search", class:"btn btn-default" %>
        <% end %>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
        <li>
          <%= link_to "Log out", logout_path, method: :delete %>
          </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%= current_user.username %>              
            <%= "Admin" if current_user.admin? %>
            <span class="caret"></span></a>
          <ul class="dropdown-menu">
             <li>
              <%= link_to "Мой профиль", user_path(current_user)%>
            </li>
            <li>
              <%= link_to "Редактировать", edit_user_path(current_user)%>
            </li>
            <li>
              <%= link_to "Новый пост", new_article_path %>
            </li>
          </ul>
        </li>
        <% else %>
        <li>
        <%= link_to "Log in", login_path %>
        </li>
        <li>
        <%= link_to "Sign up", signup_path %>
        </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NaudaBlog</title>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render "layouts/header" %>
    <% flash.each do |name, msg|%>
    <div class="alert alert-success alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <strong> <%= msg %></strong>
      </div>
    <% end %>
    <%= yield %>
</div>
</body>
</html>

app/views/pages/home.html.erb
<div class="jumbotron text-center">
   <h1>.nauda</h1>
   <%= link_to "Все посты",  articles_path, class:"btn btn-md btn-primary" %>
</div>

app/views/shared/_errors.html.erb
<% if  obj.errors.any? %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <% obj.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
    <% end %>
  </div>
  <% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
         <div class="form-group">
          <%= f.label :username %>
          <%= f.text_field :username, class:"form-control", placeholder: "Username" %>
        </div>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email,class:"form-control", rows:10, placeholder:"Email" %>
          
        </div>
        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password,class:"form-control", rows:10, placeholder:"Password" %>
          
        </div>
        <%= f.submit(@user.new_record? ? "Sign up" : "Update", :class => "btn btn-lg btn-success pull-right" )%>
  <% end %>

app/views/users/edit.html.erb
<%= render "form" %>

app/views/users/index.html.erb
<div class="container text-center">
    <%will_paginate @users%>
    <% @users.each do |user| %>
  <h1><%= link_to  user.username , user_path(user)%> </h1>
  <% if logged_in? && current_user.admin? %>
      <%= link_to "delete user", user_path(user), method: :delete %>
  <% end %>
  <% end %>
  <%will_paginate @users%>
  </div>

app/views/users/new.html.erb
<div class="col-sm-offset-2 col-sm-8">
<%= render 'shared/errors', obj: @user %>
<%=render "form" %>
</div>

app/views/users/show.html.erb
<div class="container text-center">
    
  <h1>All articles by <%= @user.username %></h1>
  <h4><%= link_to "Новый пост", new_article_path %></h4>
  <div class="col-sm-offset-3 col-sm-6">
  <%= will_paginate @user_articles%>
  <% @user_articles.each do |article| %>
  <div class="panel panel-default">
   <div class="panel-heading">
    <h2><%= article.title %></h2>
   </div>
  <div class="panel-body">
    <%= article.description%>
  </div>
  <div class="panel-footer ">
   <%= link_to "Просмотреть", article_path(article), class:"btn btn-xs btn-primary"%>
   <%= link_to "Обновить", edit_article_path(article),class:"btn btn-xs btn-success"%>
   <%= link_to "Удалить", article_path(article), 
                          method: :delete, data: {confirm: "Are you sure?"}, 
                          class:"btn btn-xs btn-danger"
                          %>
   <%#= article.updated_at.strftime("%H:%M:%S, %d/%m/%y") %>
   Last update: <%= time_ago_in_words(article.updated_at) %> ago
   by <%= article.user.username %>
  </div>
</div>
  <% end %>
   <%= will_paginate @user_articles%>
</div>